# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Номер зачетной книжки')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('study_group', models.CharField(max_length=15, verbose_name='Учебная группа')),
            ],
            options={
                'verbose_name_plural': 'Студенты',
                'verbose_name': 'Студент',
            },
        ),
        migrations.AddField(
            model_name='recordbook',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='core.Student'),
        ),
    ]
