# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordbook',
            options={'verbose_name': 'Зачетная книжка', 'verbose_name_plural': 'Зачетные книжки'},
        ),
    ]
